# Changes here will be overwritten by Copier
_commit: 3a223c6
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: jupyter
add_wiki: false
email: t.paine154@gmail.com
github: timkpaine
project_description: Automatically version jupyter notebooks in JupyterLab
project_name: jupyterlab autoversion
python_version_primary: '3.11'
team: the jupyterlab autoversion authors
